setup:
  mode: "fpt_orthant"
  n_processes: 4
  n_nodes: 1
  axes: ["sigmas", "seed"]
  chunks: [1, Null]
  dimension_names: ["fpt", "orthant"]
  outpath: "experiments/"
  condaenv: pycascades
base_config:
  type: "custom"
  dt: 0.1
  Tend: 1000000
  x_init: [-1]
  taos: [1.]
  c: [[0.25, 0.0, -0.5, 0.0]]
  A: [[0.0]]
  alphas: 2.0
  sigmas: 0.0
  seed: 42
param_grid:
  n_seeds: 1000
  orthogonal:
    sigmas: [0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22, 0.23, 0.24, 0.25,
       0.26, 0.27, 0.28, 0.29, 0.3 , 0.35, 0.4 , 0.45]