setup:
  mode: "vannes"
  n_processes: 1
  n_nodes: 550
  axes: ["alphas", "sigmas","seed", "t"]
  chunks: [1,1,5, Null]
  dimension_names: ["x"]
  outpath: "experiments/"
  condaenv: pycascades
base_config:
  type: "vannes"
  dt: 0.01
  Tend: 10000
  x_init: [90.]
  Pstart: 5.0
  Pend: 0.5
  Psteps: 451
  alphas: 2.0
  sigmas: 0.01
  seed: 42
  extra_gauss_sigma: 0.002
  # int_method: "euler"
param_grid:
  n_seeds: 200
  orthogonal:
    alphas: [1.5 , 1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ]
    sigmas: [0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 , 0.22,
       0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42, 0.44,
       0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64, 0.66,
       0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86, 0.88,
       0.9 , 0.92, 0.94, 0.96, 0.98, 1.  ]