setup:
  mode: "fpt_orthant"
  n_processes: 1
  n_nodes: 1
  axes: ["zip_id", "alphas", "sigmas", "seed"]
  chunks: [1, Null, Null, Null]
  dimension_names: ["fpt", "orthant"]
  outpath: "experiments/"
  condaenv: pycascades
base_config:
  type: "wunderling"
  dt: 10.
  Tend: 100000
  x_init: [-1, -1, -1, -1]
  GMT: 3.0
  strength: 0.75
  Tlim: [1.5, 4.0, 1.5, 4.0]
  pf_wais_to_gis: 0.1
  pf_thc_to_gis: -0.5
  pf_gis_to_thc: 0.5
  pf_wais_to_thc: 0.12
  pf_thc_to_wais: 0.05
  pf_gis_to_wais: 0.5
  pf_thc_to_amaz: 0.3
  k_wais_to_thc: -1.
  k_thc_to_amaz: -1.
  alphas: 2.0
  sigmas: 0.0
  seed: 42
param_grid:
  n_seeds: 10
  zip:
    GMT: [0.0, 3.0]
    strength: [0.0, 0.75]
  orthogonal:
    alphas: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]
    sigmas: [1, 0.5, .25, .125, .06225, 0.31225]
